---
cidr_networks:
  container: 192.168.36.0/24
  tunnel: 192.168.37.0/24
  storage: 192.168.39.0/24

used_ips:
  - "192.168.36.1"
  - "192.168.36.200,192.168.36.220"
  - "192.168.145.1,192.168.145.220"
  - "192.168.37.1"
  - "192.168.39.1"

global_overrides:
  internal_lb_vip_address: 192.168.36.201
  external_lb_vip_address: openstack.playzone.local
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "vlan8"
        ip_from_q: "container"
        container_mtu: "9000"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "vlan6"
        ip_from_q: "tunnel"
        container_mtu: "9000"
        type: "vxlan"
        range: "1:10000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "flat"
        host_bind_override: "ens256"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "provider"
        container_mtu: "9000"
        type: "vlan"
        range: "1000:3000"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "vlan4"
        container_mtu: "9000"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
#          - mons

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# rsyslog server
log_hosts:
  infra01:
    ip: 192.168.145.201

###
### OpenStack
###

# keystone
identity_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# cinder api services
storage-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203


# nova api, conductor, etc services
compute-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# heat
orchestration_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# horizon
dashboard_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# neutron server, agents (L3, etc)
network_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# ceilometer (telemetry API)
metering-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# aodh (telemetry alarm service)
metering-alarm_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# gnocchi (telemetry metrics storage)
metrics_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

# nova hypervisors
compute_hosts:
  compute01:
    ip: 192.168.145.211
  compute02:
    ip: 192.168.145.212
  compute03:
    ip: 192.168.145.213

# ceilometer compute agent (telemetry)
metering-compute_hosts:
  compute01:
    ip: 192.168.145.211
  compute02:
    ip: 192.168.145.212
  compute03:
    ip: 192.168.145.213

trove-infra_hosts:
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

image_hosts:          
  infra01:
    ip: 192.168.145.201
  infra02:
    ip: 192.168.145.202
  infra03:
    ip: 192.168.145.203

storage_hosts:
  infra01:
    ip: 192.168.145.201
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          volume_driver: cinder.volume.drivers.rbd.RBDDriver
          rbd_pool: volumes
          rbd_ceph_conf: /etc/ceph/ceph.conf 
          rbd_flatten_volume_from_snapshot: 'false'   
          rbd_max_clone_depth: 5
          rbd_store_chunk_size: 4
          rados_connect_timeout: -1
          volume_backend_name: rbd
          rbd_user: cinder
 
  infra02:
    ip: 192.168.145.202
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          volume_driver: cinder.volume.drivers.rbd.RBDDriver           
          rbd_pool: volumes
          rbd_ceph_conf: /etc/ceph/ceph.conf
          rbd_flatten_volume_from_snapshot: 'false' 
          rbd_max_clone_depth: 5 
          rbd_store_chunk_size: 4 
          rados_connect_timeout: -1 
          volume_backend_name: rbd 
          rbd_user: cinder

 
  infra03:
    ip: 192.168.145.203
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        rbd:
          volume_driver: cinder.volume.drivers.rbd.RBDDriver           
          rbd_pool: volumes
          rbd_ceph_conf: /etc/ceph/ceph.conf 
          rbd_flatten_volume_from_snapshot: 'false' 
          rbd_max_clone_depth: 5 
          rbd_store_chunk_size: 4 
          rados_connect_timeout: -1 
          volume_backend_name: rbd 
          rbd_user: cinder
